version: '3.8'

services:
  db_postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cryptoportfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  back:
    build: ./spring_java_project
    container_name: spring_backend
    restart: always
    depends_on:
      - db_postgres
    ports:
      - '8080:8080'
    environment:
      JWT_SECRET: supersecret
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:5432/cryptoportfolio
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - my_network

  front:
    build: ./example_frontend/frontend
    container_name: frontend
    restart: always
    depends_on:
      - back
    ports:
      - '3000:3000'
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - front
      - back
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
